export const HYDRATE = 'HYDRATE';

export const LOAD_CURRENT_USER_REQUEST = 'LOAD_CURRENT_USER_REQUEST';
export const LOAD_CURRENT_USER_SUCCESS = 'LOAD_CURRENT_USER_SUCCESS';
export const LOAD_CURRENT_USER_FAILURE = 'LOAD_CURRENT_USER_FAILURE';

export const UPDATE_CURRENT_USER_REQUEST = 'UPDATE_CURRENT_USER_REQUEST';
export const UPDATE_CURRENT_USER_SUCCESS = 'UPDATE_CURRENT_USER_SUCCESS';
export const UPDATE_CURRENT_USER_FAILURE = 'UPDATE_CURRENT_USER_FAILURE';

export const AUTH_USER_REQUEST = 'AUTH_USER_REQUEST';
export const AUTH_USER_SUCCESS = 'AUTH_USER_SUCCESS';
export const AUTH_USER_FAILURE = 'AUTH_USER_FAILURE';

export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAILURE = 'DELETE_USER_FAILURE';

export const LOAD_VOTE_SEASONS_REQUEST = 'LOAD_VOTE_SEASONS_REQUEST';
export const LOAD_VOTE_SEASONS_SUCCESS = 'LOAD_VOTE_SEASONS_SUCCESS';
export const LOAD_VOTE_SEASONS_FAILURE = 'LOAD_VOTE_SEASONS_FAILURE';

export const CREATE_VOTE_SEASON_REQUEST = 'CREATE_VOTE_SEASON_REQUEST';
export const CREATE_VOTE_SEASON_SUCCESS = 'CREATE_VOTE_SEASON_SUCCESS';
export const CREATE_VOTE_SEASON_FAILURE = 'CREATE_VOTE_SEASON_FAILURE';

export const UPDATE_VOTE_SEASON_REQUEST = 'UPDATE_VOTE_SEASON_REQUEST';
export const UPDATE_VOTE_SEASON_SUCCESS = 'UPDATE_VOTE_SEASON_SUCCESS';
export const UPDATE_VOTE_SEASON_FAILURE = 'UPDATE_VOTE_SEASON_FAILURE';

export const DELETE_VOTE_SEASON_REQUEST = 'DELETE_VOTE_SEASON_REQUEST';
export const DELETE_VOTE_SEASON_SUCCESS = 'DELETE_VOTE_SEASON_SUCCESS';
export const DELETE_VOTE_SEASON_FAILURE = 'DELETE_VOTE_SEASON_FAILURE';

export const LOAD_VOTE_ROUNDS_REQUEST = 'LOAD_VOTE_ROUNDS_REQUEST';
export const LOAD_VOTE_ROUNDS_SUCCESS = 'LOAD_VOTE_ROUNDS_SUCCESS';
export const LOAD_VOTE_ROUNDS_FAILURE = 'LOAD_VOTE_ROUNDS_FAILURE';

export const CREATE_VOTE_ROUND_REQUEST = 'CREATE_VOTE_ROUND_REQUEST';
export const CREATE_VOTE_ROUND_SUCCESS = 'CREATE_VOTE_ROUND_SUCCESS';
export const CREATE_VOTE_ROUND_FAILURE = 'CREATE_VOTE_ROUND_FAILURE';

export const UPDATE_VOTE_ROUND_REQUEST = 'UPDATE_VOTE_ROUND_REQUEST';
export const UPDATE_VOTE_ROUND_SUCCESS = 'UPDATE_VOTE_ROUND_SUCCESS';
export const UPDATE_VOTE_ROUND_FAILURE = 'UPDATE_VOTE_ROUND_FAILURE';

export const DELETE_VOTE_ROUND_REQUEST = 'DELETE_VOTE_ROUND_REQUEST';
export const DELETE_VOTE_ROUND_SUCCESS = 'DELETE_VOTE_ROUND_SUCCESS';
export const DELETE_VOTE_ROUND_FAILURE = 'DELETE_VOTE_ROUND_FAILURE';

export const LOAD_CURRENT_VOTE_ROUND_REQUEST = 'LOAD_CURRENT_VOTE_ROUND_REQUEST';
export const LOAD_CURRENT_VOTE_ROUND_SUCCESS = 'LOAD_CURRENT_VOTE_ROUND_SUCCESS';
export const LOAD_CURRENT_VOTE_ROUND_FAILURE = 'LOAD_CURRENT_VOTE_ROUND_FAILURE';

export const LOAD_MATCH_TEAMS_REQUEST = 'LOAD_MATCH_TEAMS_REQUEST';
export const LOAD_MATCH_TEAMS_SUCCESS = 'LOAD_MATCH_TEAMS_SUCCESS';
export const LOAD_MATCH_TEAMS_FAILURE = 'LOAD_MATCH_TEAMS_FAILURE';